// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePalSkillMap = "pal_skill_map"

// PalSkillMap 帕鲁技能表
type PalSkillMap struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PalID   int64 `gorm:"column:pal_id;not null;comment:帕鲁ID" json:"pal_id"`     // 帕鲁ID
	SkillID int64 `gorm:"column:skill_id;not null;comment:技能ID" json:"skill_id"` // 技能ID
}

// TableName PalSkillMap's table name
func (*PalSkillMap) TableName() string {
	return TableNamePalSkillMap
}
