// Code generated by goctl. DO NOT EDIT.
// Source: pal.proto

package server

import (
	"context"

	"palworld/rpc/pal/internal/logic"
	"palworld/rpc/pal/internal/svc"
	"palworld/rpc/pal/pb/pal"
)

type PalServerServer struct {
	svcCtx *svc.ServiceContext
	pal.UnimplementedPalServerServer
}

func NewPalServerServer(svcCtx *svc.ServiceContext) *PalServerServer {
	return &PalServerServer{
		svcCtx: svcCtx,
	}
}

func (s *PalServerServer) GetPal(ctx context.Context, in *pal.GetPalReq) (*pal.GetPalResp, error) {
	l := logic.NewGetPalLogic(ctx, s.svcCtx)
	return l.GetPal(in)
}

func (s *PalServerServer) ListPal(ctx context.Context, in *pal.ListPalReq) (*pal.ListPalResp, error) {
	l := logic.NewListPalLogic(ctx, s.svcCtx)
	return l.ListPal(in)
}
