// Code generated by goctl. DO NOT EDIT.
// Source: comments.proto

package server

import (
	"context"

	"palworld/rpc/comments/internal/logic"
	"palworld/rpc/comments/internal/svc"
	"palworld/rpc/comments/pb/comments"
)

type CommentsServerServer struct {
	svcCtx *svc.ServiceContext
	comments.UnimplementedCommentsServerServer
}

func NewCommentsServerServer(svcCtx *svc.ServiceContext) *CommentsServerServer {
	return &CommentsServerServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentsServerServer) AddComment(ctx context.Context, in *comments.AddCommentReq) (*comments.AddCommentResp, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

func (s *CommentsServerServer) ListComment(ctx context.Context, in *comments.ListCommentReq) (*comments.CommentListResp, error) {
	l := logic.NewListCommentLogic(ctx, s.svcCtx)
	return l.ListComment(in)
}

func (s *CommentsServerServer) DeleteComment(ctx context.Context, in *comments.DeleteCommentReq) (*comments.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
