// Code generated by goctl. DO NOT EDIT.
// Source: pal_mate.proto

package palmateserver

import (
	"context"

	"palworld/rpc/pal_mate/pb/pal_mate"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListPalMateReq  = pal_mate.ListPalMateReq
	ListPalMateResp = pal_mate.ListPalMateResp
	Pal             = pal_mate.Pal
	PalMate         = pal_mate.PalMate

	PalMateServer interface {
		ListPalMate(ctx context.Context, in *ListPalMateReq, opts ...grpc.CallOption) (*ListPalMateResp, error)
	}

	defaultPalMateServer struct {
		cli zrpc.Client
	}
)

func NewPalMateServer(cli zrpc.Client) PalMateServer {
	return &defaultPalMateServer{
		cli: cli,
	}
}

func (m *defaultPalMateServer) ListPalMate(ctx context.Context, in *ListPalMateReq, opts ...grpc.CallOption) (*ListPalMateResp, error) {
	client := pal_mate.NewPalMateServerClient(m.cli.Conn())
	return client.ListPalMate(ctx, in, opts...)
}
