// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	container_services "palworld/api/internal/handler/container_services"
	goods "palworld/api/internal/handler/goods"
	pal "palworld/api/internal/handler/pal"
	pal_mate "palworld/api/internal/handler/pal_mate"
	skill "palworld/api/internal/handler/skill"
	technology_tree "palworld/api/internal/handler/technology_tree"
	"palworld/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pal/:id",
				Handler: pal.GetPalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pal",
				Handler: pal.ListPalHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/skill",
				Handler: skill.ListSkillHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods",
				Handler: goods.ListGoodsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pal-mate",
				Handler: pal_mate.ListPalMateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/technology-tree",
				Handler: technology_tree.GetTechnologyTreeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container_services.ListContainerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers/logs",
				Handler: container_services.ContainerLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
