// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAttribute = "attribute"

// Attribute 属性
type Attribute struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name;not null;comment:名称" json:"name"`           // 名称
	Alias_       string `gorm:"column:alias;not null;comment:别名" json:"alias"`         // 别名
	Restrain     string `gorm:"column:restrain;comment:克制" json:"restrain"`            // 克制
	BeRestrained int32  `gorm:"column:be_restrained;comment:被克制" json:"be_restrained"` // 被克制
}

// TableName Attribute's table name
func (*Attribute) TableName() string {
	return TableNameAttribute
}
