// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoodsMaterial = "goods_material"

// GoodsMaterial 物品材料表
type GoodsMaterial struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodsID    int64 `gorm:"column:goods_id;not null;comment:物品ID" json:"goods_id"`       // 物品ID
	MaterialID int64 `gorm:"column:material_id;not null;comment:材料ID" json:"material_id"` // 材料ID
	Cnt        int32 `gorm:"column:cnt;not null;comment:数量" json:"cnt"`                   // 数量
}

// TableName GoodsMaterial's table name
func (*GoodsMaterial) TableName() string {
	return TableNameGoodsMaterial
}
