// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoods = "goods"

// Goods 物品
type Goods struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`                                         // 名称
	Description string         `gorm:"column:description;comment:描述" json:"description"`                                    // 描述
	Image       string         `gorm:"column:image;comment:图片" json:"image"`                                                // 图片
	Quality     int32          `gorm:"column:quality;comment:品质" json:"quality"`                                            // 品质
	Types       string         `gorm:"column:types;comment:类型" json:"types"`                                                // 类型
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Goods's table name
func (*Goods) TableName() string {
	return TableNameGoods
}
