// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTechnologyTree = "technology_tree"

// TechnologyTree 科技树
type TechnologyTree struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`                                         // 名称
	Description string         `gorm:"column:description;comment:描述" json:"description"`                                    // 描述
	Cost        int32          `gorm:"column:cost;not null;comment:消耗" json:"cost"`                                         // 消耗
	Icon        string         `gorm:"column:icon;not null;comment:图标" json:"icon"`                                         // 图标
	Ancient     bool           `gorm:"column:ancient;comment:是否古代科技" json:"ancient"`                                        // 是否古代科技
	Level       int32          `gorm:"column:level;not null;comment:解锁等级" json:"level"`                                     // 解锁等级
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName TechnologyTree's table name
func (*TechnologyTree) TableName() string {
	return TableNameTechnologyTree
}
