// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTechnologyTree = "technology_tree"

// TechnologyTree 科技树
type TechnologyTree struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null;comment:名称" json:"name"`      // 名称
	Description string `gorm:"column:description;comment:描述" json:"description"` // 描述
	Cost        int32  `gorm:"column:cost;not null;comment:消耗" json:"cost"`      // 消耗
	Icon        string `gorm:"column:icon;not null;comment:图标" json:"icon"`      // 图标
	Ancient     bool   `gorm:"column:ancient;comment:是否古代科技" json:"ancient"`     // 是否古代科技
	Level       int32  `gorm:"column:level;not null;comment:解锁等级" json:"level"`  // 解锁等级
}

// TableName TechnologyTree's table name
func (*TechnologyTree) TableName() string {
	return TableNameTechnologyTree
}
