// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePal = "pal"

// Pal 帕鲁
type Pal struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Number       string `gorm:"column:number;not null;comment:编号" json:"number"`                 // 编号
	Name         string `gorm:"column:name;not null;comment:名字" json:"name"`                     // 名字
	EnName       string `gorm:"column:en_name;not null;comment:英文名字" json:"en_name"`             // 英文名字
	Icon         string `gorm:"column:icon;not null;comment:头像" json:"icon"`                     // 头像
	AttributeIds string `gorm:"column:attribute_ids;not null;comment:属性id" json:"attribute_ids"` // 属性id
	Hp           int32  `gorm:"column:hp;not null;comment:血量" json:"hp"`                         // 血量
	Energy       int32  `gorm:"column:energy;not null;comment:攻击力" json:"energy"`                // 攻击力
	Defensively  int32  `gorm:"column:defensively;not null;comment:防御力" json:"defensively"`      // 防御力
	Abilities    string `gorm:"column:abilities;comment:工作能力" json:"abilities"`                  // 工作能力
	Eat          int32  `gorm:"column:eat;comment:消耗" json:"eat"`                                // 消耗
	PassiveSkill int32  `gorm:"column:passive_skill;comment:被动技能" json:"passive_skill"`          // 被动技能
	Level        int32  `gorm:"column:level;comment:级别（孵蛋大小）" json:"level"`                      // 级别（孵蛋大小）
}

// TableName Pal's table name
func (*Pal) TableName() string {
	return TableNamePal
}
