// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkill = "skill"

// Skill 技能
type Skill struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null;comment:名称" json:"name"`                   // 名称
	Description string `gorm:"column:description;not null;comment:描述" json:"description"`     // 描述
	Ct          int32  `gorm:"column:ct;not null;comment:冷却" json:"ct"`                       // 冷却
	Power       int32  `gorm:"column:power;not null;comment:威力" json:"power"`                 // 威力
	AttributeID int32  `gorm:"column:attribute_id;not null;comment:属性ID" json:"attribute_id"` // 属性ID
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
