// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: pal.proto

package pal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeId int64  `protobuf:"varint,1,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListPalReq) Reset() {
	*x = ListPalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPalReq) ProtoMessage() {}

func (x *ListPalReq) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPalReq.ProtoReflect.Descriptor instead.
func (*ListPalReq) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{0}
}

func (x *ListPalReq) GetAttributeId() int64 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

func (x *ListPalReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number       string     `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Name         string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon         string     `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	AttributeIds []int32    `protobuf:"varint,5,rep,packed,name=attribute_ids,json=attributeIds,proto3" json:"attribute_ids,omitempty"`
	Abilities    []*Ability `protobuf:"bytes,6,rep,name=abilities,proto3" json:"abilities,omitempty"`
}

func (x *ListPal) Reset() {
	*x = ListPal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPal) ProtoMessage() {}

func (x *ListPal) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPal.ProtoReflect.Descriptor instead.
func (*ListPal) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{1}
}

func (x *ListPal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListPal) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ListPal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPal) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ListPal) GetAttributeIds() []int32 {
	if x != nil {
		return x.AttributeIds
	}
	return nil
}

func (x *ListPal) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

type ListPalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ListPal `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListPalResp) Reset() {
	*x = ListPalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPalResp) ProtoMessage() {}

func (x *ListPalResp) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPalResp.ProtoReflect.Descriptor instead.
func (*ListPalResp) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{2}
}

func (x *ListPalResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPalResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPalResp) GetData() []*ListPal {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPalReq) Reset() {
	*x = GetPalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPalReq) ProtoMessage() {}

func (x *GetPalReq) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPalReq.ProtoReflect.Descriptor instead.
func (*GetPalReq) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{3}
}

func (x *GetPalReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Pal   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPalResp) Reset() {
	*x = GetPalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPalResp) ProtoMessage() {}

func (x *GetPalResp) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPalResp.ProtoReflect.Descriptor instead.
func (*GetPalResp) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{4}
}

func (x *GetPalResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPalResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPalResp) GetData() *Pal {
	if x != nil {
		return x.Data
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ct          int32  `protobuf:"varint,4,opt,name=ct,proto3" json:"ct,omitempty"`
	Power       int32  `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	AttributeId int32  `protobuf:"varint,6,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{5}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetCt() int32 {
	if x != nil {
		return x.Ct
	}
	return 0
}

func (x *Skill) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Skill) GetAttributeId() int32 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

type Ability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icon  int32  `protobuf:"varint,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level int64  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Ability) Reset() {
	*x = Ability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{6}
}

func (x *Ability) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Pal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number       string     `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Name         string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon         string     `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	AttributeIds []int32    `protobuf:"varint,5,rep,packed,name=attribute_ids,json=attributeIds,proto3" json:"attribute_ids,omitempty"`
	Hp           int32      `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Energy       int32      `protobuf:"varint,7,opt,name=energy,proto3" json:"energy,omitempty"`
	Defensively  int32      `protobuf:"varint,8,opt,name=defensively,proto3" json:"defensively,omitempty"`
	Abilities    []*Ability `protobuf:"bytes,9,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Eat          int32      `protobuf:"varint,10,opt,name=eat,proto3" json:"eat,omitempty"`
	Description  string     `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Passive      string     `protobuf:"bytes,12,opt,name=passive,proto3" json:"passive,omitempty"`
	PassiveDesc  string     `protobuf:"bytes,14,opt,name=passive_desc,json=passiveDesc,proto3" json:"passive_desc,omitempty"`
	Skills       []*Skill   `protobuf:"bytes,15,rep,name=skills,proto3" json:"skills,omitempty"`
}

func (x *Pal) Reset() {
	*x = Pal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pal) ProtoMessage() {}

func (x *Pal) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pal.ProtoReflect.Descriptor instead.
func (*Pal) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{7}
}

func (x *Pal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pal) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Pal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pal) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Pal) GetAttributeIds() []int32 {
	if x != nil {
		return x.AttributeIds
	}
	return nil
}

func (x *Pal) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Pal) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *Pal) GetDefensively() int32 {
	if x != nil {
		return x.Defensively
	}
	return 0
}

func (x *Pal) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *Pal) GetEat() int32 {
	if x != nil {
		return x.Eat
	}
	return 0
}

func (x *Pal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pal) GetPassive() string {
	if x != nil {
		return x.Passive
	}
	return ""
}

func (x *Pal) GetPassiveDesc() string {
	if x != nil {
		return x.PassiveDesc
	}
	return ""
}

func (x *Pal) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type GetPalByIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetPalByIdsReq) Reset() {
	*x = GetPalByIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPalByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPalByIdsReq) ProtoMessage() {}

func (x *GetPalByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPalByIdsReq.ProtoReflect.Descriptor instead.
func (*GetPalByIdsReq) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{8}
}

func (x *GetPalByIdsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetPalByIdsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*PalIdsInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPalByIdsResp) Reset() {
	*x = GetPalByIdsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPalByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPalByIdsResp) ProtoMessage() {}

func (x *GetPalByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPalByIdsResp.ProtoReflect.Descriptor instead.
func (*GetPalByIdsResp) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{9}
}

func (x *GetPalByIdsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPalByIdsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPalByIdsResp) GetData() []*PalIdsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type PalIdsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *PalIdsInfo) Reset() {
	*x = PalIdsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PalIdsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalIdsInfo) ProtoMessage() {}

func (x *PalIdsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalIdsInfo.ProtoReflect.Descriptor instead.
func (*PalIdsInfo) Descriptor() ([]byte, []int) {
	return file_pal_proto_rawDescGZIP(), []int{10}
}

func (x *PalIdsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PalIdsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PalIdsInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_pal_proto protoreflect.FileDescriptor

var file_pal_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x61, 0x6c,
	0x22, 0x43, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x61, 0x6c, 0x2e,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x22, 0x5d, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x61, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x1b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x50,
	0x61, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x96, 0x01, 0x0a, 0x05, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49,
	0x64, 0x22, 0x47, 0x0a, 0x07, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x85, 0x03, 0x0a, 0x03, 0x50,
	0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x6c, 0x79, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x6c,
	0x79, 0x12, 0x2a, 0x0a, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x61, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x22,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x64, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c,
	0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x50, 0x61, 0x6c, 0x49,
	0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x0a,
	0x50, 0x61, 0x6c, 0x49, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x29, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x12, 0x0e, 0x2e, 0x70,
	0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70,
	0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x61, 0x6c, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x61, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x70, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x61, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pal_proto_rawDescOnce sync.Once
	file_pal_proto_rawDescData = file_pal_proto_rawDesc
)

func file_pal_proto_rawDescGZIP() []byte {
	file_pal_proto_rawDescOnce.Do(func() {
		file_pal_proto_rawDescData = protoimpl.X.CompressGZIP(file_pal_proto_rawDescData)
	})
	return file_pal_proto_rawDescData
}

var file_pal_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pal_proto_goTypes = []interface{}{
	(*ListPalReq)(nil),      // 0: pal.ListPalReq
	(*ListPal)(nil),         // 1: pal.ListPal
	(*ListPalResp)(nil),     // 2: pal.ListPalResp
	(*GetPalReq)(nil),       // 3: pal.GetPalReq
	(*GetPalResp)(nil),      // 4: pal.GetPalResp
	(*Skill)(nil),           // 5: pal.Skill
	(*Ability)(nil),         // 6: pal.Ability
	(*Pal)(nil),             // 7: pal.Pal
	(*GetPalByIdsReq)(nil),  // 8: pal.GetPalByIdsReq
	(*GetPalByIdsResp)(nil), // 9: pal.GetPalByIdsResp
	(*PalIdsInfo)(nil),      // 10: pal.PalIdsInfo
}
var file_pal_proto_depIdxs = []int32{
	6,  // 0: pal.ListPal.abilities:type_name -> pal.Ability
	1,  // 1: pal.ListPalResp.data:type_name -> pal.ListPal
	7,  // 2: pal.GetPalResp.data:type_name -> pal.Pal
	6,  // 3: pal.Pal.abilities:type_name -> pal.Ability
	5,  // 4: pal.Pal.skills:type_name -> pal.Skill
	10, // 5: pal.GetPalByIdsResp.data:type_name -> pal.PalIdsInfo
	3,  // 6: pal.PalServer.GetPal:input_type -> pal.GetPalReq
	0,  // 7: pal.PalServer.ListPal:input_type -> pal.ListPalReq
	8,  // 8: pal.PalServer.GetPalByIds:input_type -> pal.GetPalByIdsReq
	4,  // 9: pal.PalServer.GetPal:output_type -> pal.GetPalResp
	2,  // 10: pal.PalServer.ListPal:output_type -> pal.ListPalResp
	9,  // 11: pal.PalServer.GetPalByIds:output_type -> pal.GetPalByIdsResp
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pal_proto_init() }
func file_pal_proto_init() {
	if File_pal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPalByIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPalByIdsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PalIdsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pal_proto_goTypes,
		DependencyIndexes: file_pal_proto_depIdxs,
		MessageInfos:      file_pal_proto_msgTypes,
	}.Build()
	File_pal_proto = out.File
	file_pal_proto_rawDesc = nil
	file_pal_proto_goTypes = nil
	file_pal_proto_depIdxs = nil
}
