// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"palworld/rpc/goods/internal/logic"
	"palworld/rpc/goods/internal/svc"
	"palworld/rpc/goods/pb/goods"
)

type GoodsServerServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServerServer
}

func NewGoodsServerServer(svcCtx *svc.ServiceContext) *GoodsServerServer {
	return &GoodsServerServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServerServer) ListGoods(ctx context.Context, in *goods.ListGoodsReq) (*goods.ListGoodsResp, error) {
	l := logic.NewListGoodsLogic(ctx, s.svcCtx)
	return l.ListGoods(in)
}

func (s *GoodsServerServer) GetGoods(ctx context.Context, in *goods.GetGoodsReq) (*goods.GetGoodsResp, error) {
	l := logic.NewGetGoodsLogic(ctx, s.svcCtx)
	return l.GetGoods(in)
}
