// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComments = "comments"

// Comments 评论
type Comments struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID          int64          `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                        // 用户id
	Category        string         `gorm:"column:category;not null;comment:类型" json:"category"`                        // 类型
	ObjectID        int64          `gorm:"column:object_id;not null;comment:对象id" json:"object_id"`                    // 对象id
	Content         string         `gorm:"column:content;not null;comment:内容" json:"content"`                          // 内容
	ParentCommentID int64          `gorm:"column:parent_comment_id;comment:父评论id" json:"parent_comment_id"`            // 父评论id
	RootCommentID   int64          `gorm:"column:root_comment_id;comment:根评论id" json:"root_comment_id"`                // 根评论id
	CreatedAt       time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                           // 删除时间
}

// TableName Comments's table name
func (*Comments) TableName() string {
	return TableNameComments
}
